### ISSUE TITLE
How do I get play to play an Internet streaming radio url?

### ISSUE THREAD

**Issue by rollynoel** [caumons/play#4]
omxplayer is happy to handle them.
Thanks for your help.

**Comment by caumons** [comment]
Hi Rolly,

Which command are you trying to execute? Are you getting any errors? Do you
need any omxplayer flag not supported by play?

Cheers.

**Comment by rollynoel** [comment]
Thanks for getting back to me Enric.
Your app is wonderfully equipped to collect the names of local files to play.
What I'm wanting to use it for is to collect the URLs of Internet streaming radio stations
for example:
File1=http://us4.internet-radio.com:8266/stream
Title1=Smooth Jazz Florida

**Comment by caumons** [comment]
Hi @rollynoel!

I've just released v1.2 that supports streaming. You can even create and save playlists containing both local and streaming files.

Let me know it works :)

Cheers!

**Comment by rollynoel** [comment]
Thanks for the add-on.
It seems to sometimes switch to the next stream in the playlist on its own.
Entering an index number changes the volume instead.
How do I delete an entry from a playlist (where is the file so I can edit it?).
Thanks for the help.

**Comment by rollynoel** [comment]
I see where I had it wrong - it only handles an index number after you have entered a control-c

**Comment by caumons** [comment]
Hi Rolly,

While a file is playing, omxplayer handles the keyboard inputs. To get back
to play, you have to hit control + c to actually kill the omxplayer process
launched by play. I recommend you to fully read the provided README.md file.

You currently can't delete a single file from a playlist, so I suggest you
to delete and create a new playlist without that file. The playlist is
saved into a SQLite database, so I don't recommend you to modify it unless
you really know what you are doing, or you could easily corrupt the data.

Regarding the streaming files playlist automatically skipping to the next
file, It may be caused if the omxplayer reaches the end of the file and
exits the playback. In that case, play automatically jumps to the next
file. That could happen if you're using a slow Internet connection and/or
the server you are connecting to has small bandwidth. Could you please send
me some examples of failing streams? Could you please try playing the
problematic streaming files using omxplayer directly and see if it
eventually stops playing? Omxplayer provides some buffering flags, so you
could try if some combination works better and then they could be added to
play:

    --audio_fifo n Size of audio output fifo in seconds
    --video_fifo n Size of video output fifo in MB
    --audio_queue n Size of audio input queue in MB
    --video_queue n Size of video input queue in MB
    --threshold n Amount of buffered data required to finish buffering [s]

Cheers.
