### ISSUE TITLE
Play in the background

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [caumons/play#5]
Is it possible to have play run the background, that is, run headless? Use case would be a script running play to play a playlist.

My specific use case is to run play when a USB is plugged into my Raspberry Pi. I have play's output being sent to the journal to see what's going on. Everything runs fine as expected, then play lists the playlist contents and states it's playing one of the files, but then says bye immediately. Watching htop, play appears in htop's list for about a second and then disappears.

I would need a way for play to run headless, even if that means it can't be controlled, at least for now.

**Comment by caumons** [comment]
In order to run play in the background you can use programs such as Byobu or Screen that will allow you to detach from the terminal running the process.
